### ISSUE TITLE
Resync with Chiadog v0.7.0 - pools support

### ISSUE THREAD

**Issue by guydavis** [langhorst/flaxdog#1]
With Flax network updating to [v0.1.1](https://github.com/Flax-Network/flax-blockchain/releases/tag/0.1.1) and promising plotnft support in their upcoming v0.2.0 release, would it be possible to resync Flaxdog with the latest Chiadog [release v0.7.0](https://github.com/martomi/chiadog/releases/tag/v0.7.0) at the same time?  The latest Chiadog release adds support for pools.

**Comment by langhorst** [comment]
This is on my list to tackle very, very soon.

**Comment by guydavis** [comment]
No worries.  I've been running my [own fork of Chiadog](https://github.com/guydavis/chiadog/tree/dev) for many months now.  

Sorry, I forgot to close this stale request.  Doing that now.
